image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # className: "nginx"
  # annotations: {}
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

podDisruptionBudget: {}
  # minAvailable: 1
  # maxUnavailable: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

environment: []
  # - name: Database__DatabaseName
  #   value: MyDatabase
  # - name: Database__ConnectionString
  #   valueFromSecret: DatabaseConnectionString

secrets: {}
  # DatabaseConnectionString: "{{DATABASE_CONNECTION_STRING}}"
