{{- if .Values.secrets }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end}}
{{- end }}
